wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    start_time: 1670588419.628862
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 23
      4: 3.7.0
      5: 0.13.6
      8:
      - 3
      - 5
      10:
      - 9
